version: '3.7'

services:
  kadena-devnet:
    container_name: kadena-devnet
    image: kadena/devnet:latest
    volumes:
      - kadena_devnet:/data
    ports:
      - 8080:8080

  pact-core:
    container_name: pact-core
    image: gielinorian/pact-core
    volumes:
      - .:/data
    entrypoint: ["./tests/run_off_chain.sh"]

volumes:
  kadena_devnet:
