name: Test Gielinorian Contracts

on: push

jobs:
  test-pact-v4:
    runs-on: ubuntu-latest
    env:
      PACT_VERSION: v4.13.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Pact-core ${{ env.PACT_VERSION }} image
        run: docker pull gielinorian/pact-core:${{ env.PACT_VERSION }}

      - name: Run tests
        run: |
          docker run -v $(pwd):/data gielinorian/pact-core:${{ env.PACT_VERSION }} ./tests/run_off_chain.sh

      - name: Validate Tests
        run: |
          if grep -q "FAILURE" ./out/test_output.log; then
            exit 1
          fi

  test-pact-v5:
    runs-on: ubuntu-latest
    env:
      PACT_VERSION: v5.0.0-beta

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Pact-core ${{ env.PACT_VERSION }} image
        run: docker pull gielinorian/pact-core:${{ env.PACT_VERSION }}

      - name: Run tests
        run: |
          docker run -v $(pwd):/data gielinorian/pact-core:${{ env.PACT_VERSION }} ./tests/run_off_chain.sh

      - name: Validate Tests
        run: |
          if grep -q "FAILURE" ./out/test_output.log; then
            exit 1
          fi

