name: Test Gielinorian Contracts

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Pact
        run: |
          wget -nv https://github.com/kadena-io/pact/releases/download/v4.10.0/pact-4.10.0-linux-22.04.zip
          unzip pact-4.10.0-linux-22.04.zip pact
          chmod +x pact
      
      - name: Run tests
        run: |
          PACT_PATH=./pact
          ./tests/run_tests.sh | tee output.txt
          grep -q "Load fail" output.txt && echo exit 1 || exit 0
    